### ISSUE TITLE
Sometimes messages are not positioned properly

### ISSUE THREAD

**Issue by mtodor** [thunder/select2#20]
Here is gif:
![select2_ko](https://user-images.githubusercontent.com/3965286/42999241-4746d23e-8c1d-11e8-9653-37eb2bb76fce.gif)

Problematic thing is that, message is exactly over other field and it's really difficult to notice displacement.

**Comment by chrfritsch** [comment]
This is a library issue. Not a drupal integration

https://github.com/select2/select2/issues/4614
